## Практическое задание №3

In [1]:
import numpy as np

### 1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

#### Решение

Из методички:
Матрицу $A$  можно умножить не на всякую матрицу $B$: необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.

В частности, определить оба произведения $A⋅B$ и $B⋅A$ можно только в случае, когда число столбцов $A$ совпадает с числом строк $B$, а число строк $A$ совпадает с числом столбцов $B$. В этом случае матрицы $A⋅B$ и $B⋅A$ будут квадратными. Их порядок в общем случае будет различным и будет совпадать только в случае квадратных матриц $A$ и $B$.

#### Таким образом:
а) произведение $AB$ - не определено, произведение  $BA$ - не определено

б) произведение $AB$ - определено = матрица $5 \times 5$, произведение $BA$ - не определено

в) произведение $AB$ - определено = матрица $3 \times 3$, произведение $BA$ - определено = матрица $8 \times 8$

г) произведения $AB$ и $BA$ - определены = матрицы $4 \times 4$

### 2. Найти сумму и произведение матриц 
$A=\begin{pmatrix}
1;&-2\\ 
3;&0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 ;& -1\\ 
0 ;& 5
\end{pmatrix}.$

#### Решение

$A + B=\begin{pmatrix}
1 + 4 &; -2 + (-1)\\ 
3 + 0 &; 0 + 5
\end{pmatrix}$ = $\begin{pmatrix}
5 &; -3\\ 
3 &; 5
\end{pmatrix}.$

$AB=\begin{pmatrix}
1 \cdot 4 - 2 \cdot 0  &; 1 \cdot -1 - 2 \cdot 5\\ 
3 \cdot 4 + 0 \cdot 0  &; 3 \cdot -1 + 0 \cdot 4
\end{pmatrix}$ = $\begin{pmatrix}
4 &; -11\\ 
12 &; -3
\end{pmatrix}.$

#### Проверка

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')
print(f'Матрица С = A*B\n{np.dot(a, b)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица С = A*B
[[  4 -11]
 [ 12  -3]]


### 3. 
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 ;& 7\\ 
3 ;& -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 ;& 5\\ 
2 ;& -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 ;& -4\\ 
1 ;& 1
\end{pmatrix}.$

#### Решение


$3A - 2B + 4C =\begin{pmatrix}
3 \cdot 1 - 2 \cdot 0 + 4 \cdot 2;& 3 \cdot 7\ - 2 \cdot 5\ + 4 \cdot -4\\ 
3 \cdot 3 - 2 \cdot 2 + 4 \cdot 1 ;& 3 \cdot -6 - 2 \cdot -1 + 4 \cdot 1
\end{pmatrix}$ = $\begin{pmatrix}
11 ;& -5\\ 
9 ;& -12
\end{pmatrix}$


#### Проверка

In [3]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
с = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С\n{с}\n')
print(f'Матрица 3𝐴−2𝐵+4𝐶\n{3*a - 2* b + 4*с}')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица С
[[ 2 -4]
 [ 1  1]]

Матрица 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


### 4. 
Дана матрица $A=\begin{pmatrix}
4 ;& 1\\ 
5 ;& -2\\ 
2 ;& 3
\end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

#### Решение

$AA^T=\begin{pmatrix}
4 ;& 1\\ 
5 ;& -2\\ 
2 ;& 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 ;& 5 ;& 2\\ 
1 ;& -2 ;& 3
\end{pmatrix} $ = $\begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 ;& 4 \cdot 5 + 1 \cdot -2 ;& 4 \cdot 2 + 1 \cdot 3\\ 
5 \cdot 4 - 2 \cdot 1 ;& 5 \cdot 5 - 2 \cdot -2 ;& 5 \cdot 2 - 2 \cdot 3\\ 
2 \cdot 4 + 3 \cdot 1 ;& 2 \cdot 5 + 3 \cdot -2 ;& 2 \cdot 2 + 3 \cdot 3
\end{pmatrix} = 
\begin{pmatrix}
17 ;& 18 ;& 11\\ 
18 ;& 29 ;& 4\\ 
11 ;& 4 ;& 13
\end{pmatrix} $

$A^TA=\begin{pmatrix}
4 ;& 5 ;& 2\\ 
1 ;& -2 ;& 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 ;& 1\\ 
5 ;& -2\\ 
2 ;& 3
\end{pmatrix} $ = $\begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 ;& 4 \cdot 1 + 5 \cdot -2 + 2 \cdot 3\\ 
1 \cdot 4 - 2 \cdot 5 + 3 \cdot 2 ;& 1 \cdot 1 - 2 \cdot -2 + 3 \cdot 3
\end{pmatrix} = 
\begin{pmatrix}
45 ;& 0\\ 
0 ;& 14
\end{pmatrix} $

#### Проверка

In [4]:
a = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица:\n{a}')
print(f'Произведение A*AT:\n{np.dot(a, a.T)}')
print(f'Произведение AT*A:\n{np.dot(a.T, a)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Произведение A*AT:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение AT*A:
[[45  0]
 [ 0 14]]


### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

#### Решение

In [5]:
def matrix_mult(matrix_A, matrix_B):
    sum_ = 0     
    matrix_ = []    
    matrix_С = [] 
    if len(matrix_B)!=len(matrix_A[0]): 
        print("Матрицы не могут быть перемножены")       
    else:
        for z in range(0, len(matrix_A)):
            for j in range(0,len(matrix_B[0])):
                for i in range(0,len(matrix_A[0])):
                   sum_ += matrix_A[z][i]*matrix_B[i][j]
                matrix_.append(sum_)
                sum_ = 0
            matrix_С.append(matrix_)
            matrix_ = []           
    return matrix_С

#### Проверка

In [6]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
matrix_mult(a, b)

[[4, -11], [12, -3]]