## Практическое задание №4

In [1]:
import numpy as np

### 1. Вычислить определитель:

a)

$$\begin{vmatrix}
sinx ;& -cosx\\ 
cosx ;& sinx
\end{vmatrix};$$
б)

$$\begin{vmatrix}
4 ;& 2 ;& 3\\ 
0 ;& 5 ;& 1\\ 
0 ;& 0 ;& 9
\end{vmatrix};$$
в)

$$\begin{vmatrix}
1 ;& 2 ;& 3\\ 
4 ;& 5 ;& 6\\ 
7 ;& 8 ;& 9
\end{vmatrix}.$$

#### Решение

а) $\begin{vmatrix}
sinx ;& -cosx\\ 
cosx ;& sinx
\end{vmatrix} = sinx \cdot sinx + cosx \cdot cosx = sin^2x +  cos^2x = 1$

б) $\begin{vmatrix}
4 ;& 2 ;& 3\\ 
0 ;& 5 ;& 1\\ 
0 ;& 0 ;& 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$

в) $\begin{vmatrix}
1 ;& 2 ;& 3\\ 
4 ;& 5 ;& 6\\ 
7 ;& 8 ;& 9
\end{vmatrix} = 1 \cdot \begin{vmatrix}
5 ;& 6\\ 
8 ;& 9
\end{vmatrix}  - 2 \cdot \begin{vmatrix}
4  ;& 6\\ 
7  ;& 9
\end{vmatrix} + 3 \cdot \begin{vmatrix}
4 ;& 5\\ 
7 ;& 8
\end{vmatrix} = -3 + 12 - 9 = 0  $

#### Проверка

In [2]:
#a = np.array([[np.sin(), -np.cos()], [np.cos(), np.sin()]])
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#print(f'Матрица:\n{a}')
#print(f'Определитель:\n{np.linalg.det(a):.0f}')
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')
print(f'Матрица:\n{c}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180
Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


### 2. Определитель матрицы $A$ равен $4$. Найти:
а) $det(A^{2})$;

б) $det(A^{T})$;

в) $det(2A)$.

#### Решение

а) $det(A^{2}) = det(AA) = |A| \cdot |A| = 4 \cdot 4 = 16$;

б) $det(A^{T}) = det(A)  = 4$;

в) $det(2A) = 2^2 \cdot |A|  = 16 $.

### 3. Доказать, что матрица вырожденная

$$\begin{pmatrix}
-2 ;& 7 ;& -3\\ 
4 ;& -14 ;& 6\\ 
-3 ;& 7 ;& 13
\end{pmatrix}$$

#### Решение

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

Т.к. первая строка = (-2) умножить на вторую строку, т.е. они линейно зависимы, то определитель = 0

#### Проверка

$\begin{vmatrix}
-2 ;& 7 ;& -3\\ 
4 ;& -14 ;& 6\\ 
3 ;& 7 ;& 13
\end{vmatrix} = -2 \cdot \begin{vmatrix}
-14 ;& 6\\ 
7 ;& 13
\end{vmatrix}  - 7 \cdot \begin{vmatrix}
4  ;& 6\\ 
3  ;& 13
\end{vmatrix} - 3 \cdot \begin{vmatrix}
4 ;& -14\\ 
3 ;& 7
\end{vmatrix} = -2 \cdot (-182 -42) -7 \cdot (52 - 18) -3 \cdot (28 + 52) = 448 - 238 - 210 = 0  $

In [3]:
а = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'Матрица:\n{а}')
print(f'Определитель:\n{np.linalg.det(а):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


### 4. Найти ранг матрицы:

а) $\begin{pmatrix}
1 ;& 2 ;& 3\\ 
1 ;& 1 ;& 1\\ 
2 ;& 3 ;& 4
\end{pmatrix};$

б) $\begin{pmatrix}
0 ;& 0 ;& 2 ;& 1\\ 
0 ;& 0 ;& 2 ;& 2\\ 
0 ;& 0 ;& 4 ;& 3\\ 
2 ;& 3 ;& 5 ;& 6
\end{pmatrix}.$

#### Решение

а) Третья строка =  первой строке с +1, то есть третья строка является линейной комбинацией первой строки, поэтому её можно отбросить. Получается надо посчитать ранг матрицы $\begin{pmatrix}
1 ;& 2 ;& 3\\ 
1 ;& 1 ;& 1\\
\end{pmatrix} $

Ранг =  2

б) Третья строка равна сумме первой и второй строк, поэтому её можно отбросить.
Получается надо посчитать ранг матрицы $\begin{pmatrix}
0 ;& 0 ;& 2 ;& 1\\ 
0 ;& 0 ;& 2 ;& 2\\
2 ;& 3 ;& 5 ;& 6
\end{pmatrix}.$ 

Строки матрицы - линейно независимы, следовательно ранг = 3.

#### Проверка

In [4]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}')
print(f'Матрица:\n{b}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(b)}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2
Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
